package fi.vm.yti.comments.api.exception;

public abstract class ErrorConstants {

    public static final String ERR_MSG_USER_401 = "ERR_MSG_USER_401";
    public static final String ERR_MSG_USER_404 = "ERR_MSG_USER_404";
    public static final String ERR_MSG_USER_406 = "ERR_MSG_USER_406";
    public static final String ERR_MSG_USER_500 = "ERR_MSG_USER_500";
    public static final String ERR_MSG_USER_END_BEFORE_START_DATE = "ERR_MSG_USER_END_BEFORE_START_DATE";
    public static final String ERR_MSG_USER_CANNOT_MODIFY_EXISTING_COMMENT = "ERR_MSG_USER_CANNOT_MODIFY_EXISTING_COMMENT";
    public static final String ERR_MSG_USER_CANNOT_CREATE_EMPTY_COMMENT = "ERR_MSG_USER_CANNOT_CREATE_EMPTY_COMMENT";
    public static final String ERR_MSG_USER_CANNOT_MODIFY_EXISTING_COMMENTTHREAD = "ERR_MSG_USER_CANNOT_MODIFY_EXISTING_COMMENTTHREAD";
    public static final String ERR_MSG_USER_INVALID_PARENTCOMMENT = "ERR_MSG_USER_INVALID_PARENTCOMMENT";
    public static final String ERR_MSG_USER_NOT_ALLOWED_TO_MODIFY_CONTENT_FROM_ANOTHER_USER = "ERR_MSG_USER_NOT_ALLOWED_TO_MODIFY_CONTENT_FROM_ANOTHER_USER";
    public static final String ERR_MSG_COMMENT_HAS_INVALID_COMMENTTHREAD_ID = "ERR_MSG_COMMENT_HAS_INVALID_COMMENTTHREAD_ID";
    public static final String ERR_MSG_COMMENT_DOES_NOT_HAVE_COMMENT_THREAD = "ERR_MSG_COMMENT_DOES_NOT_HAVE_COMMENTTHREAD";
    public static final String ERR_MSG_NO_RESOURCES_TO_COMMENT_STATUS_CHANGE_NOT_ALLOWED = "ERR_MSG_NO_RESOURCES_TO_COMMENT_STATUS_CHANGE_NOT_ALLOWED";
    public static final String ERR_MSG_USER_COMMENTTHREAD_HAS_INVALID_COMMENTROUND_ID = "ERR_MSG_USER_COMMENTTHREAD_HAS_INVALID_COMMENTROUND_ID";
    public static final String ERR_MSG_INVALID_SOURCE_DATA = "ERR_MSG_INVALID_SOURCE_DATA";
    public static final String ERR_MSG_INVALID_ID = "ERR_MSG_INVALID_ID";
    public static final String ERR_MSG_USER_PROPOSED_STATUS_REQUIRED = "ERR_MSG_USER_PROPOSED_STATUS_REQUIRED";
    public static final String ERR_MSG_USER_OTHER_USER_ALREADY_RESPONDED_TO_THIS_COMMENT_CANT_MODIFY_OR_DELETE = "ERR_MSG_USER_OTHER_USER_ALREADY_RESPONDED_TO_THIS_COMMENT_CANT_MODIFY_OR_DELETE";
    public static final String ERR_MSG_CANT_REACH_MESSAGING_API = "ERR_MSG_CANT_REACH_MESSAGING_API";

    private ErrorConstants() {
    }
}
